// tests/verify/mermaid-render.test.ts
// Tests for the deterministic Mermaid renderer (Pitfall 12 prevention).
// RED phase: tests written before implementation.
//
// Implements: Pitfall 12 (mermaid renderer ships in Phase 1 for Phase 3 consumption),
//             D-12 (verify --golden scope includes mermaid-render)

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "../..");

const INPUT_MMD = join(ROOT, "evals/fixtures/golden/mermaid-render/input.mmd");
const EXPECTED_SVG = join(
  ROOT,
  "evals/fixtures/golden/mermaid-render/expected.svg"
);

describe("mermaid-render: script structure", () => {
  it("mermaid-render.mjs exists", () => {
    const p = join(ROOT, "assets/scripts/mermaid-render.mjs");
    expect(existsSync(p)).toBe(true);
  });

  it("uses @mermaid-js/mermaid-cli", async () => {
    const src = await readFile(
      join(ROOT, "assets/scripts/mermaid-render.mjs"),
      "utf8"
    );
    expect(src).toContain("@mermaid-js/mermaid-cli");
  });

  it("accepts --input and --output CLI args", async () => {
    const src = await readFile(
      join(ROOT, "assets/scripts/mermaid-render.mjs"),
      "utf8"
    );
    expect(src).toContain("--input");
    expect(src).toContain("--output");
  });

  it("contains deterministicIds configuration", async () => {
    const src = await readFile(
      join(ROOT, "assets/scripts/mermaid-render.mjs"),
      "utf8"
    );
    expect(src).toContain("deterministicIds");
  });

  it("contains deterministicIDSeed configuration", async () => {
    const src = await readFile(
      join(ROOT, "assets/scripts/mermaid-render.mjs"),
      "utf8"
    );
    expect(src).toContain("deterministicIDSeed");
  });
});

describe("mermaid-render: fixture files", () => {
  it("input.mmd exists and contains a stateDiagram", async () => {
    expect(existsSync(INPUT_MMD)).toBe(true);
    const content = await readFile(INPUT_MMD, "utf8");
    expect(content).toContain("stateDiagram");
  });

  it("expected.svg exists and contains <svg", async () => {
    // expected.svg is generated by the mermaid renderer
    // It should exist after implementation creates it
    if (existsSync(EXPECTED_SVG)) {
      const content = await readFile(EXPECTED_SVG, "utf8");
      expect(content).toContain("<svg");
    } else {
      // acceptable for first RED run - fixture needs generation
      expect(existsSync(INPUT_MMD)).toBe(true);
    }
  });
});

describe("mermaid-render: determinism", () => {
  it("produces byte-identical SVG output on two consecutive renders", async () => {
    // @ts-ignore TS7016: no declaration for .mjs script
    const mod: { renderMermaidFile: (input: string, output: string) => Promise<void> } =
      await import("../../assets/scripts/mermaid-render.mjs");

    if (typeof mod.renderMermaidFile !== "function") {
      // Script may not export renderMermaidFile if not yet implemented
      // This test will fail RED - that's correct
      expect(typeof mod.renderMermaidFile).toBe("function");
      return;
    }

    const tempDir = await mkdir(join(tmpdir(), `mmd-test-${Date.now()}`), {
      recursive: true,
    }).then(() => join(tmpdir(), `mmd-test-${Date.now()}`));
    await mkdir(tempDir, { recursive: true });

    const out1 = join(tempDir, "render1.svg");
    const out2 = join(tempDir, "render2.svg");

    try {
      await mod.renderMermaidFile(INPUT_MMD, out1);
      await mod.renderMermaidFile(INPUT_MMD, out2);

      const svg1 = await readFile(out1, "utf8");
      const svg2 = await readFile(out2, "utf8");

      const hash1 = createHash("sha256").update(svg1).digest("hex");
      const hash2 = createHash("sha256").update(svg2).digest("hex");

      expect(hash1).toBe(hash2);
      expect(svg1).toContain("<svg");
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
  }, 60000); // timeout 60s — browser launch can be slow
});
